### ISSUE TITLE
Installation process for Employee Kudos Template won't proceed beyond environment selection

### ISSUE THREAD

**Issue by jukkan** [microsoft/Templates-for-Power-Platform#12] opened 2023-06-07 16:09 UTC
After clicking the link on the [AppSource page](https://aka.ms/AccessEmployeeKudosTemplate), I'm taken to the environment selection page in Power Platform Admin Center. Selecting any environment and clicking "Install" will just result in a spinner displaying over the button for 1 second, then disappearing. No error messages, nothing.

![image](https://github.com/microsoft/Templates-for-Power-Platform/assets/10254155/336d2d6f-1855-4d6d-8d67-5450b98b5ba3)

What am I doing wrong?

**Comment by tshanep** [comment] 2023-06-07 17:08
Interesting, we haven't run into a scenario like that before. Have you been able to install other solutions into this environment before?

**Comment by tshanep** [comment] 2023-06-07 17:29
In the meantime, there is an alternate way to install Kudos. You can do a manual install using the typical "Import Solution" capability in an environment. Kudos consists of two solutions - a base solution that is shared with other HR solutions and the Kudos solution. Install the Base solution first as Kudos depends on it. Here are links the solution zip files:

1. [Base Solution Link](https://github.com/microsoft/Templates-for-Power-Platform/releases/download/0.0.2/mpa_EmployeeExperienceBase_managed.zip)
2. [Kudos Solution Link](https://github.com/microsoft/Templates-for-Power-Platform/releases/download/0.0.2/mpa_Kudos_managed.zip)

**Comment by laublarsen** [comment] 2023-06-08 06:11
I am seeing the same problem. I try to deploy to Europe Region and the Application cannot be found (located through HAR analysis).
So either the solution is not deployed to Europe region or it is not deployed correctly

**Comment by laublarsen** [comment] 2023-06-08 06:25
I tried to import the 2 solutions manually.
The first was fine
The Second came up with this error
![image](https://github.com/microsoft/Templates-for-Power-Platform/assets/135946519/48429ab5-8092-48a8-978c-c51deab2f916)

**Comment by tshanep** [comment] 2023-06-08 18:24
We're trying to track down why that error occurs sometimes. Despite the error, the solution should still work.

**Comment by laublarsen** [comment] 2023-06-09 06:03
I am seeing errors in the Flow Kudo App - Share Kudo with Sender, Assign to Recipient

I have checked and rechecked the setup and all looks ok

Principal with id 3d6352e7-40f1-eb11-bacb-00224883415f does not have ReadAccess right(s) for record with id 5943d0e1-8a06-ee11-8f6e-6045bd8c5f83 of entity mpa_kudo. Details: {"CallerPrincipal":{"PrincipalId":"3d6352e7-40f1-eb11-bacb-00224883415f","Type":8,"IsUserPrincipal":true},"OwnerPrincipal":{"PrincipalId":"fc6252e7-40f1-eb11-bacb-00224883415f","Type":8,"IsUserPrincipal":true},"ObjectId":"5943d0e1-8a06-ee11-8f6e-6045bd8c5f83","ObjectTypeCode":11344,"EntityName":"mpa_kudo","ObjectBusinessUnitId":"a9dc2c36-56ed-eb11-bacb-000d3abd1381","RightsToCheck":"ReadAccess","RoleAccessRights":"None","PoaAccessRights":"None","HsmAccessRights":"None","GrantedAccessRights":"None","Messages":["BasicMinimumPrivilegeDepthRequired = None","EntityUserGroupRights = None","LocalMinimumPrivilegeDepthRequiredRights = ReadAccess","SecLib::AccessCheckEx2 failed. Owner Data: roleCount=6, privilegeCount=10430, accessMode=0, MetadataCachePrivilegesCount=10432, businessUnitId=a9dc2c36-56ed-eb11-bacb-000d3abd1381; Principal Data: roleCount=2, privilegeCount=496, accessMode=0, MetadataCachePrivilegesCount=10432, businessUnitId=a9dc2c36-56ed-eb11-bacb-000d3abd1381"],"EntityOwnershipTypeMask":1,"CallerInfo":{"IsSystemUser":false,"IsSupportUser":false,"IsAdministrator":false,"IsCustomizer":false,"IsDisabled":false,"IsIntegrationUser":false,"Teams":null,"Roles":null},"ReadOnlyState":"UserAndOrgFullAccess","IsHsmEnabled":false,"HsmInfo":null,"AccessOrigin":null}

![image](https://github.com/microsoft/Templates-for-Power-Platform/assets/135946519/0770a203-62c8-4f0e-bd24-eba09bff3efd)

**Comment by tshanep** [comment] 2023-06-09 06:08
Thanks for sharing!

Did you create an Access Team called "Kudos-ReadAccessTeam"?

**Comment by tshanep** [comment] 2023-06-09 06:10
Also, what security roles does the user who is creating the Kudos have in this case?

**Comment by laublarsen** [comment] 2023-06-09 06:24
Yes. I created the access team. It looks like that each time I submit a new team is created in the app. Don’t know if this is by design. The user has employee role

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tshanep** [comment] 2023-06-09 06:26
Does the user also have "Basic User" role?

**Comment by laublarsen** [comment] 2023-06-09 06:27
Yes

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Closed** 2023-08-14 23:09 UTC
