### ISSUE TITLE
Hardware and IT Asset Management Template - Subgrid for Purchase Orders

### ISSUE THREAD

**Issue by bwatson23** [microsoft/Templates-for-Power-Platform#53] opened 2023-11-14 01:24 UTC
Hi,

Looks like the subgrid for the business group entity is navigating to budget instead of purchase orders in the bottom left grid.

<img width="1759" alt="Business Group - Subgrid" src="https://github.com/microsoft/Templates-for-Power-Platform/assets/150640493/c7947d53-4028-4f9f-a6d6-473e071f7258">

Kind regards,
Ben

**Comment by robinsonshields** [comment] 2023-11-15 18:01
Thank you for posting this issue. We have looked into in and have verified the behavior. We are looking into a fix for this issue and will redeploy once the issue is resolved.

**Comment by robinsonshields** [comment] 2024-02-16 14:50
This issue has been fixed, and new version of the app has been published to App Source and is ready for use. Thank you for pointing out this issue.

**Closed by robinsonshields** 2024-02-16 14:50 UTC
